### PR TITLE
Update API WordPress version to v5.3.2

### LINKED ISSUE #177: Upgrade to WordPress 5.3
Need to update Core in the Tide repo which means figuring out what changed in the REST API in 5.0+ that is causing breakage. We are stuck using an old version of Core until we have time to troubleshoot that. It’s going to take some domain knowledge of Tide and REST API to fix it. It would be great if someone figured it out but it’s probably not obvious.

### PR DESCRIPTION
**Pull request by derekherman**
Replaces #192 and relates to wptide/wp-tide-api#29 and wptide/wporg-tide-api#4.
One of many PRs to close #177.

### CODE REVIEW

**Comment by jeffpaul** [comment]
Closing in favor of #192, which we'll bump to WP 5.3 and maintain the fuller comment history there.

**Comment by derekherman** [comment]
@jeffpaul the branch in #192  is not in our org so the tests will always fail. I'm working on fixing this PR now.

**Comment by derekherman** [comment]
@pierlon If you could test this PR that would be helpful. You may need to update the submodules as I changed the commit hash on those. `git submodule update --init --recursive` should do the trick once you've pulled the changes.

**Review by pierlon — APPROVED** [review]
No issues with APIs to report, :shipit:.

**Comment by jeffpaul** [comment]
@derekherman looks like @pierlon is good on this, you ok to merge?

**Pull request merged**
