### PR TITLE
Adda a minimal composer.json file.

### PR DESCRIPTION
**Pull request by mikeschinkel**
### Description of the Change

Adds a minimal `composer.json` file so that this repo can be composed into an existing project.

### Alternate Designs

n/a

### Benefits

Allows other projects to view Tide as a dependency.

### Possible Drawbacks

I cannot imagine any.

### Verification Process

I ran Composer on a project that references my fork to ensure it could compose with this `composer.json`.

What process did you follow to verify that your chan

### Applicable Issues

n/a

### CODE REVIEW

**Comment by valendesigns** [comment]
Not sure why the build is failing. I'll look into it later, seems something odd is happening with goveralls.

**Comment by jeffpaul** [comment]
@mikeschinkel thanks for contributing! We're working to wrap up the GCP migration heading into WCEU, so I suspect the soonest we'd be able to take a serious look at the build failure is mid-June. In the meantime, please let me know if you've identified other Tide roadmap items as it relates to WPLib Box... thanks!

**Comment by mikeschinkel** [comment]
@jeffpaul Thanks Jeff.  Talking to @valendesigns on Slack, I think I need to wait at least until some of the dependencies on AWS and other external services are completed before I can realistically make it work.  

But I was able to do is replicate the _(WP-based)_ API in our Box, or at least I think I did; hard to say without ability to test it. 

BTW, say hello to @sirjonathan for me...

**Comment by valendesigns** [comment]
Closing, the branch that this would be merged into is stale.

**Pull request closed without merging**
